/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Answer { 'answer' : string, 'questionId' : bigint }
export interface AuthCredentials { 'username' : string, 'password' : string }
export type ExternalBlob = Uint8Array;
export interface Media {
  'blob' : ExternalBlob,
  'description' : string,
  'mediaType' : { 'audio' : null } |
    { 'image' : null },
}
export interface Question {
  'id' : bigint,
  'marks' : bigint,
  'media' : [] | [Media],
  'text' : string,
  'correctAnswer' : string,
  'questionType' : QuestionType,
  'options' : Array<string>,
}
export type QuestionType = { 'sentenceCompletion' : null } |
  { 'shortAnswer' : null } |
  { 'longAnswer' : null } |
  { 'multipleChoice' : null } |
  { 'matching' : null } |
  { 'trueFalseNotGiven' : null };
export interface StudentResponse {
  'id' : bigint,
  'totalCorrect' : bigint,
  'studentName' : string,
  'submissionTimestamp' : bigint,
  'answers' : Array<Answer>,
  'totalScore' : bigint,
  'batchNumber' : string,
  'timeTaken' : bigint,
  'estimatedBand' : number,
  'testId' : bigint,
  'totalWrong' : bigint,
}
export interface Test {
  'id' : bigint,
  'title' : string,
  'testType' : TestType,
  'instructions' : string,
  'questions' : Array<Question>,
}
export type TestType = { 'reading' : null } |
  { 'mixed' : null } |
  { 'writing' : null } |
  { 'listening' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'createStudentResponse' : ActorMethod<[StudentResponse], undefined>,
  'createTest' : ActorMethod<[AuthCredentials, Test], undefined>,
  'deleteStudentResponse' : ActorMethod<[bigint], undefined>,
  'deleteTest' : ActorMethod<[AuthCredentials, bigint], undefined>,
  'getAllStudentResponses' : ActorMethod<[], Array<StudentResponse>>,
  'getAllTests' : ActorMethod<[], Array<Test>>,
  'getResponsesByBatch' : ActorMethod<[string], Array<StudentResponse>>,
  'getResponsesByTest' : ActorMethod<[bigint], Array<StudentResponse>>,
  'getSortedResponses' : ActorMethod<[], Array<StudentResponse>>,
  'getStudentResponse' : ActorMethod<[bigint], [] | [StudentResponse]>,
  'getTest' : ActorMethod<[bigint], [] | [Test]>,
  'searchResponsesByName' : ActorMethod<[string], Array<StudentResponse>>,
  'updateStudentResponse' : ActorMethod<[bigint, StudentResponse], undefined>,
  'updateTest' : ActorMethod<[AuthCredentials, bigint, Test], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];