/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Answer = IDL.Record({
  'answer' : IDL.Text,
  'questionId' : IDL.Nat,
});
export const StudentResponse = IDL.Record({
  'id' : IDL.Nat,
  'totalCorrect' : IDL.Nat,
  'studentName' : IDL.Text,
  'submissionTimestamp' : IDL.Int,
  'answers' : IDL.Vec(Answer),
  'totalScore' : IDL.Nat,
  'batchNumber' : IDL.Text,
  'timeTaken' : IDL.Nat,
  'estimatedBand' : IDL.Float64,
  'testId' : IDL.Nat,
  'totalWrong' : IDL.Nat,
});
export const AuthCredentials = IDL.Record({
  'username' : IDL.Text,
  'password' : IDL.Text,
});
export const TestType = IDL.Variant({
  'reading' : IDL.Null,
  'mixed' : IDL.Null,
  'writing' : IDL.Null,
  'listening' : IDL.Null,
});
export const QuestionType = IDL.Variant({
  'sentenceCompletion' : IDL.Null,
  'shortAnswer' : IDL.Null,
  'longAnswer' : IDL.Null,
  'multipleChoice' : IDL.Null,
  'matching' : IDL.Null,
  'trueFalseNotGiven' : IDL.Null,
});
export const Question = IDL.Record({
  'id' : IDL.Nat,
  'marks' : IDL.Nat,
  'text' : IDL.Text,
  'correctAnswer' : IDL.Text,
  'questionType' : QuestionType,
  'options' : IDL.Vec(IDL.Text),
});
export const Test = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'testType' : TestType,
  'instructions' : IDL.Text,
  'questions' : IDL.Vec(Question),
});

export const idlService = IDL.Service({
  'createStudentResponse' : IDL.Func([StudentResponse], [], []),
  'createTest' : IDL.Func([AuthCredentials, Test], [], []),
  'deleteStudentResponse' : IDL.Func([IDL.Nat], [], []),
  'deleteTest' : IDL.Func([AuthCredentials, IDL.Nat], [], []),
  'getAllStudentResponses' : IDL.Func(
      [],
      [IDL.Vec(StudentResponse)],
      ['query'],
    ),
  'getAllTests' : IDL.Func([], [IDL.Vec(Test)], ['query']),
  'getResponsesByBatch' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(StudentResponse)],
      ['query'],
    ),
  'getResponsesByTest' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(StudentResponse)],
      ['query'],
    ),
  'getSortedResponses' : IDL.Func([], [IDL.Vec(StudentResponse)], ['query']),
  'getStudentResponse' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(StudentResponse)],
      ['query'],
    ),
  'getTest' : IDL.Func([IDL.Nat], [IDL.Opt(Test)], ['query']),
  'searchResponsesByName' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(StudentResponse)],
      ['query'],
    ),
  'updateStudentResponse' : IDL.Func([IDL.Nat, StudentResponse], [], []),
  'updateTest' : IDL.Func([AuthCredentials, IDL.Nat, Test], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Answer = IDL.Record({ 'answer' : IDL.Text, 'questionId' : IDL.Nat });
  const StudentResponse = IDL.Record({
    'id' : IDL.Nat,
    'totalCorrect' : IDL.Nat,
    'studentName' : IDL.Text,
    'submissionTimestamp' : IDL.Int,
    'answers' : IDL.Vec(Answer),
    'totalScore' : IDL.Nat,
    'batchNumber' : IDL.Text,
    'timeTaken' : IDL.Nat,
    'estimatedBand' : IDL.Float64,
    'testId' : IDL.Nat,
    'totalWrong' : IDL.Nat,
  });
  const AuthCredentials = IDL.Record({
    'username' : IDL.Text,
    'password' : IDL.Text,
  });
  const TestType = IDL.Variant({
    'reading' : IDL.Null,
    'mixed' : IDL.Null,
    'writing' : IDL.Null,
    'listening' : IDL.Null,
  });
  const QuestionType = IDL.Variant({
    'sentenceCompletion' : IDL.Null,
    'shortAnswer' : IDL.Null,
    'longAnswer' : IDL.Null,
    'multipleChoice' : IDL.Null,
    'matching' : IDL.Null,
    'trueFalseNotGiven' : IDL.Null,
  });
  const Question = IDL.Record({
    'id' : IDL.Nat,
    'marks' : IDL.Nat,
    'text' : IDL.Text,
    'correctAnswer' : IDL.Text,
    'questionType' : QuestionType,
    'options' : IDL.Vec(IDL.Text),
  });
  const Test = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'testType' : TestType,
    'instructions' : IDL.Text,
    'questions' : IDL.Vec(Question),
  });
  
  return IDL.Service({
    'createStudentResponse' : IDL.Func([StudentResponse], [], []),
    'createTest' : IDL.Func([AuthCredentials, Test], [], []),
    'deleteStudentResponse' : IDL.Func([IDL.Nat], [], []),
    'deleteTest' : IDL.Func([AuthCredentials, IDL.Nat], [], []),
    'getAllStudentResponses' : IDL.Func(
        [],
        [IDL.Vec(StudentResponse)],
        ['query'],
      ),
    'getAllTests' : IDL.Func([], [IDL.Vec(Test)], ['query']),
    'getResponsesByBatch' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(StudentResponse)],
        ['query'],
      ),
    'getResponsesByTest' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(StudentResponse)],
        ['query'],
      ),
    'getSortedResponses' : IDL.Func([], [IDL.Vec(StudentResponse)], ['query']),
    'getStudentResponse' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(StudentResponse)],
        ['query'],
      ),
    'getTest' : IDL.Func([IDL.Nat], [IDL.Opt(Test)], ['query']),
    'searchResponsesByName' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(StudentResponse)],
        ['query'],
      ),
    'updateStudentResponse' : IDL.Func([IDL.Nat, StudentResponse], [], []),
    'updateTest' : IDL.Func([AuthCredentials, IDL.Nat, Test], [], []),
  });
};

export const init = ({ IDL }) => { return []; };