/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface AuthCredentials {
    username: string;
    password: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Feedback {
    text: string;
    submittedBy: string;
}
export interface Test {
    id: bigint;
    title: string;
    testType: TestType;
    instructions: string;
    questions: Array<Question>;
}
export interface StudentResponse {
    id: bigint;
    totalCorrect: bigint;
    studentName: string;
    submissionTimestamp: bigint;
    answers: Array<Answer>;
    feedback?: Feedback;
    totalScore: bigint;
    batchNumber: string;
    timeTaken: bigint;
    estimatedBand: number;
    testId: bigint;
    totalWrong: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Question {
    id: bigint;
    marks: bigint;
    media?: Media;
    text: string;
    correctAnswer: string;
    questionType: QuestionType;
    options: Array<string>;
}
export interface Media {
    blob: ExternalBlob;
    description: string;
    mediaType: Variant_audio_image;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface Answer {
    answer: string;
    questionId: bigint;
}
export enum QuestionType {
    sentenceCompletion = "sentenceCompletion",
    shortAnswer = "shortAnswer",
    longAnswer = "longAnswer",
    multipleChoice = "multipleChoice",
    matching = "matching",
    trueFalseNotGiven = "trueFalseNotGiven"
}
export enum TestType {
    reading = "reading",
    mixed = "mixed",
    writing = "writing",
    listening = "listening"
}
export enum Variant_audio_image {
    audio = "audio",
    image = "image"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    createStudentResponse(response: StudentResponse): Promise<void>;
    createTest(creds: AuthCredentials, test: Test): Promise<void>;
    deleteStudentResponse(id: bigint): Promise<void>;
    deleteTest(creds: AuthCredentials, id: bigint): Promise<void>;
    getAllStudentResponses(): Promise<Array<StudentResponse>>;
    getAllTests(): Promise<Array<Test>>;
    getResponsesByBatch(batchNumber: string): Promise<Array<StudentResponse>>;
    getResponsesByTest(testId: bigint): Promise<Array<StudentResponse>>;
    getSortedResponses(): Promise<Array<StudentResponse>>;
    getStudentResponse(id: bigint): Promise<StudentResponse | null>;
    getTest(id: bigint): Promise<Test | null>;
    searchResponsesByName(searchTerm: string): Promise<Array<StudentResponse>>;
    submitFeedback(creds: AuthCredentials, responseId: bigint, feedbackText: string): Promise<void>;
    updateStudentResponse(id: bigint, updatedResponse: StudentResponse): Promise<void>;
    updateTest(creds: AuthCredentials, id: bigint, updatedTest: Test): Promise<void>;
}
import type { Answer as _Answer, ExternalBlob as _ExternalBlob, Feedback as _Feedback, Media as _Media, Question as _Question, QuestionType as _QuestionType, StudentResponse as _StudentResponse, Test as _Test, TestType as _TestType, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async createStudentResponse(arg0: StudentResponse): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createStudentResponse(to_candid_StudentResponse_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStudentResponse(to_candid_StudentResponse_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createTest(arg0: AuthCredentials, arg1: Test): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createTest(arg0, await to_candid_Test_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTest(arg0, await to_candid_Test_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteStudentResponse(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStudentResponse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStudentResponse(arg0);
            return result;
        }
    }
    async deleteTest(arg0: AuthCredentials, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTest(arg0, arg1);
            return result;
        }
    }
    async getAllStudentResponses(): Promise<Array<StudentResponse>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStudentResponses();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStudentResponses();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTests(): Promise<Array<Test>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTests();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTests();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getResponsesByBatch(arg0: string): Promise<Array<StudentResponse>> {
        if (this.processError) {
            try {
                const result = await this.actor.getResponsesByBatch(arg0);
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResponsesByBatch(arg0);
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getResponsesByTest(arg0: bigint): Promise<Array<StudentResponse>> {
        if (this.processError) {
            try {
                const result = await this.actor.getResponsesByTest(arg0);
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResponsesByTest(arg0);
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSortedResponses(): Promise<Array<StudentResponse>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSortedResponses();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSortedResponses();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudentResponse(arg0: bigint): Promise<StudentResponse | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentResponse(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentResponse(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTest(arg0: bigint): Promise<Test | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTest(arg0);
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTest(arg0);
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchResponsesByName(arg0: string): Promise<Array<StudentResponse>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchResponsesByName(arg0);
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchResponsesByName(arg0);
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitFeedback(arg0: AuthCredentials, arg1: bigint, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitFeedback(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitFeedback(arg0, arg1, arg2);
            return result;
        }
    }
    async updateStudentResponse(arg0: bigint, arg1: StudentResponse): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStudentResponse(arg0, to_candid_StudentResponse_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStudentResponse(arg0, to_candid_StudentResponse_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateTest(arg0: AuthCredentials, arg1: bigint, arg2: Test): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTest(arg0, arg1, await to_candid_Test_n10(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTest(arg0, arg1, await to_candid_Test_n10(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
}
async function from_candid_ExternalBlob_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_Media_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Media): Promise<Media> {
    return await from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_QuestionType_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuestionType): QuestionType {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
async function from_candid_Question_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Question): Promise<Question> {
    return await from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_StudentResponse_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StudentResponse): StudentResponse {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_TestType_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TestType): TestType {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
async function from_candid_Test_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Test): Promise<Test> {
    return await from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Feedback]): Feedback | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Media]): Promise<Media | null> {
    return value.length === 0 ? null : await from_candid_Media_n36(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StudentResponse]): StudentResponse | null {
    return value.length === 0 ? null : from_candid_StudentResponse_n24(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Test]): Promise<Test | null> {
    return value.length === 0 ? null : await from_candid_Test_n28(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    totalCorrect: bigint;
    studentName: string;
    submissionTimestamp: bigint;
    answers: Array<_Answer>;
    feedback: [] | [_Feedback];
    totalScore: bigint;
    batchNumber: string;
    timeTaken: bigint;
    estimatedBand: number;
    testId: bigint;
    totalWrong: bigint;
}): {
    id: bigint;
    totalCorrect: bigint;
    studentName: string;
    submissionTimestamp: bigint;
    answers: Array<Answer>;
    feedback?: Feedback;
    totalScore: bigint;
    batchNumber: string;
    timeTaken: bigint;
    estimatedBand: number;
    testId: bigint;
    totalWrong: bigint;
} {
    return {
        id: value.id,
        totalCorrect: value.totalCorrect,
        studentName: value.studentName,
        submissionTimestamp: value.submissionTimestamp,
        answers: value.answers,
        feedback: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.feedback)),
        totalScore: value.totalScore,
        batchNumber: value.batchNumber,
        timeTaken: value.timeTaken,
        estimatedBand: value.estimatedBand,
        testId: value.testId,
        totalWrong: value.totalWrong
    };
}
async function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    testType: _TestType;
    instructions: string;
    questions: Array<_Question>;
}): Promise<{
    id: bigint;
    title: string;
    testType: TestType;
    instructions: string;
    questions: Array<Question>;
}> {
    return {
        id: value.id,
        title: value.title,
        testType: from_candid_TestType_n30(_uploadFile, _downloadFile, value.testType),
        instructions: value.instructions,
        questions: await from_candid_vec_n32(_uploadFile, _downloadFile, value.questions)
    };
}
async function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    marks: bigint;
    media: [] | [_Media];
    text: string;
    correctAnswer: string;
    questionType: _QuestionType;
    options: Array<string>;
}): Promise<{
    id: bigint;
    marks: bigint;
    media?: Media;
    text: string;
    correctAnswer: string;
    questionType: QuestionType;
    options: Array<string>;
}> {
    return {
        id: value.id,
        marks: value.marks,
        media: record_opt_to_undefined(await from_candid_opt_n35(_uploadFile, _downloadFile, value.media)),
        text: value.text,
        correctAnswer: value.correctAnswer,
        questionType: from_candid_QuestionType_n40(_uploadFile, _downloadFile, value.questionType),
        options: value.options
    };
}
async function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    blob: _ExternalBlob;
    description: string;
    mediaType: {
        audio: null;
    } | {
        image: null;
    };
}): Promise<{
    blob: ExternalBlob;
    description: string;
    mediaType: Variant_audio_image;
}> {
    return {
        blob: await from_candid_ExternalBlob_n38(_uploadFile, _downloadFile, value.blob),
        description: value.description,
        mediaType: from_candid_variant_n39(_uploadFile, _downloadFile, value.mediaType)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    reading: null;
} | {
    mixed: null;
} | {
    writing: null;
} | {
    listening: null;
}): TestType {
    return "reading" in value ? TestType.reading : "mixed" in value ? TestType.mixed : "writing" in value ? TestType.writing : "listening" in value ? TestType.listening : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    audio: null;
} | {
    image: null;
}): Variant_audio_image {
    return "audio" in value ? Variant_audio_image.audio : "image" in value ? Variant_audio_image.image : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sentenceCompletion: null;
} | {
    shortAnswer: null;
} | {
    longAnswer: null;
} | {
    multipleChoice: null;
} | {
    matching: null;
} | {
    trueFalseNotGiven: null;
}): QuestionType {
    return "sentenceCompletion" in value ? QuestionType.sentenceCompletion : "shortAnswer" in value ? QuestionType.shortAnswer : "longAnswer" in value ? QuestionType.longAnswer : "multipleChoice" in value ? QuestionType.multipleChoice : "matching" in value ? QuestionType.matching : "trueFalseNotGiven" in value ? QuestionType.trueFalseNotGiven : value;
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StudentResponse>): Array<StudentResponse> {
    return value.map((x)=>from_candid_StudentResponse_n24(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Test>): Promise<Array<Test>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Test_n28(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Question>): Promise<Array<Question>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Question_n33(_uploadFile, _downloadFile, x)));
}
async function to_candid_ExternalBlob_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_Media_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Media): Promise<_Media> {
    return await to_candid_record_n18(_uploadFile, _downloadFile, value);
}
function to_candid_QuestionType_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuestionType): _QuestionType {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
async function to_candid_Question_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Question): Promise<_Question> {
    return await to_candid_record_n16(_uploadFile, _downloadFile, value);
}
function to_candid_StudentResponse_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StudentResponse): _StudentResponse {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_TestType_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TestType): _TestType {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
async function to_candid_Test_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Test): Promise<_Test> {
    return await to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    testType: TestType;
    instructions: string;
    questions: Array<Question>;
}): Promise<{
    id: bigint;
    title: string;
    testType: _TestType;
    instructions: string;
    questions: Array<_Question>;
}> {
    return {
        id: value.id,
        title: value.title,
        testType: to_candid_TestType_n12(_uploadFile, _downloadFile, value.testType),
        instructions: value.instructions,
        questions: await to_candid_vec_n14(_uploadFile, _downloadFile, value.questions)
    };
}
async function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    marks: bigint;
    media?: Media;
    text: string;
    correctAnswer: string;
    questionType: QuestionType;
    options: Array<string>;
}): Promise<{
    id: bigint;
    marks: bigint;
    media: [] | [_Media];
    text: string;
    correctAnswer: string;
    questionType: _QuestionType;
    options: Array<string>;
}> {
    return {
        id: value.id,
        marks: value.marks,
        media: value.media ? candid_some(await to_candid_Media_n17(_uploadFile, _downloadFile, value.media)) : candid_none(),
        text: value.text,
        correctAnswer: value.correctAnswer,
        questionType: to_candid_QuestionType_n21(_uploadFile, _downloadFile, value.questionType),
        options: value.options
    };
}
async function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    blob: ExternalBlob;
    description: string;
    mediaType: Variant_audio_image;
}): Promise<{
    blob: _ExternalBlob;
    description: string;
    mediaType: {
        audio: null;
    } | {
        image: null;
    };
}> {
    return {
        blob: await to_candid_ExternalBlob_n19(_uploadFile, _downloadFile, value.blob),
        description: value.description,
        mediaType: to_candid_variant_n20(_uploadFile, _downloadFile, value.mediaType)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    totalCorrect: bigint;
    studentName: string;
    submissionTimestamp: bigint;
    answers: Array<Answer>;
    feedback?: Feedback;
    totalScore: bigint;
    batchNumber: string;
    timeTaken: bigint;
    estimatedBand: number;
    testId: bigint;
    totalWrong: bigint;
}): {
    id: bigint;
    totalCorrect: bigint;
    studentName: string;
    submissionTimestamp: bigint;
    answers: Array<_Answer>;
    feedback: [] | [_Feedback];
    totalScore: bigint;
    batchNumber: string;
    timeTaken: bigint;
    estimatedBand: number;
    testId: bigint;
    totalWrong: bigint;
} {
    return {
        id: value.id,
        totalCorrect: value.totalCorrect,
        studentName: value.studentName,
        submissionTimestamp: value.submissionTimestamp,
        answers: value.answers,
        feedback: value.feedback ? candid_some(value.feedback) : candid_none(),
        totalScore: value.totalScore,
        batchNumber: value.batchNumber,
        timeTaken: value.timeTaken,
        estimatedBand: value.estimatedBand,
        testId: value.testId,
        totalWrong: value.totalWrong
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TestType): {
    reading: null;
} | {
    mixed: null;
} | {
    writing: null;
} | {
    listening: null;
} {
    return value == TestType.reading ? {
        reading: null
    } : value == TestType.mixed ? {
        mixed: null
    } : value == TestType.writing ? {
        writing: null
    } : value == TestType.listening ? {
        listening: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_audio_image): {
    audio: null;
} | {
    image: null;
} {
    return value == Variant_audio_image.audio ? {
        audio: null
    } : value == Variant_audio_image.image ? {
        image: null
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuestionType): {
    sentenceCompletion: null;
} | {
    shortAnswer: null;
} | {
    longAnswer: null;
} | {
    multipleChoice: null;
} | {
    matching: null;
} | {
    trueFalseNotGiven: null;
} {
    return value == QuestionType.sentenceCompletion ? {
        sentenceCompletion: null
    } : value == QuestionType.shortAnswer ? {
        shortAnswer: null
    } : value == QuestionType.longAnswer ? {
        longAnswer: null
    } : value == QuestionType.multipleChoice ? {
        multipleChoice: null
    } : value == QuestionType.matching ? {
        matching: null
    } : value == QuestionType.trueFalseNotGiven ? {
        trueFalseNotGiven: null
    } : value;
}
async function to_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Question>): Promise<Array<_Question>> {
    return await Promise.all(value.map(async (x)=>await to_candid_Question_n15(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
