/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface AuthCredentials {
    username: string;
    password: string;
}
export interface Answer {
    answer: string;
    questionId: bigint;
}
export interface Test {
    id: bigint;
    title: string;
    testType: TestType;
    instructions: string;
    questions: Array<Question>;
}
export interface StudentResponse {
    id: bigint;
    totalCorrect: bigint;
    studentName: string;
    submissionTimestamp: bigint;
    answers: Array<Answer>;
    totalScore: bigint;
    batchNumber: string;
    timeTaken: bigint;
    estimatedBand: number;
    testId: bigint;
    totalWrong: bigint;
}
export interface Question {
    id: bigint;
    marks: bigint;
    text: string;
    correctAnswer: string;
    questionType: QuestionType;
    options: Array<string>;
}
export enum QuestionType {
    sentenceCompletion = "sentenceCompletion",
    shortAnswer = "shortAnswer",
    longAnswer = "longAnswer",
    multipleChoice = "multipleChoice",
    matching = "matching",
    trueFalseNotGiven = "trueFalseNotGiven"
}
export enum TestType {
    reading = "reading",
    mixed = "mixed",
    writing = "writing",
    listening = "listening"
}
export interface backendInterface {
    createStudentResponse(response: StudentResponse): Promise<void>;
    createTest(creds: AuthCredentials, test: Test): Promise<void>;
    deleteStudentResponse(id: bigint): Promise<void>;
    deleteTest(creds: AuthCredentials, id: bigint): Promise<void>;
    getAllStudentResponses(): Promise<Array<StudentResponse>>;
    getAllTests(): Promise<Array<Test>>;
    getResponsesByBatch(batchNumber: string): Promise<Array<StudentResponse>>;
    getResponsesByTest(testId: bigint): Promise<Array<StudentResponse>>;
    getSortedResponses(): Promise<Array<StudentResponse>>;
    getStudentResponse(id: bigint): Promise<StudentResponse | null>;
    getTest(id: bigint): Promise<Test | null>;
    searchResponsesByName(searchTerm: string): Promise<Array<StudentResponse>>;
    updateStudentResponse(id: bigint, updatedResponse: StudentResponse): Promise<void>;
    updateTest(creds: AuthCredentials, id: bigint, updatedTest: Test): Promise<void>;
}
import type { Question as _Question, QuestionType as _QuestionType, StudentResponse as _StudentResponse, Test as _Test, TestType as _TestType } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createStudentResponse(arg0: StudentResponse): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createStudentResponse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStudentResponse(arg0);
            return result;
        }
    }
    async createTest(arg0: AuthCredentials, arg1: Test): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createTest(arg0, to_candid_Test_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTest(arg0, to_candid_Test_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteStudentResponse(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStudentResponse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStudentResponse(arg0);
            return result;
        }
    }
    async deleteTest(arg0: AuthCredentials, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTest(arg0, arg1);
            return result;
        }
    }
    async getAllStudentResponses(): Promise<Array<StudentResponse>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStudentResponses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStudentResponses();
            return result;
        }
    }
    async getAllTests(): Promise<Array<Test>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTests();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTests();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getResponsesByBatch(arg0: string): Promise<Array<StudentResponse>> {
        if (this.processError) {
            try {
                const result = await this.actor.getResponsesByBatch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResponsesByBatch(arg0);
            return result;
        }
    }
    async getResponsesByTest(arg0: bigint): Promise<Array<StudentResponse>> {
        if (this.processError) {
            try {
                const result = await this.actor.getResponsesByTest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResponsesByTest(arg0);
            return result;
        }
    }
    async getSortedResponses(): Promise<Array<StudentResponse>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSortedResponses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSortedResponses();
            return result;
        }
    }
    async getStudentResponse(arg0: bigint): Promise<StudentResponse | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentResponse(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentResponse(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTest(arg0: bigint): Promise<Test | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTest(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTest(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchResponsesByName(arg0: string): Promise<Array<StudentResponse>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchResponsesByName(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchResponsesByName(arg0);
            return result;
        }
    }
    async updateStudentResponse(arg0: bigint, arg1: StudentResponse): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStudentResponse(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStudentResponse(arg0, arg1);
            return result;
        }
    }
    async updateTest(arg0: AuthCredentials, arg1: bigint, arg2: Test): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTest(arg0, arg1, to_candid_Test_n1(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTest(arg0, arg1, to_candid_Test_n1(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
}
function from_candid_QuestionType_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuestionType): QuestionType {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Question_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Question): Question {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_TestType_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TestType): TestType {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Test_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Test): Test {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StudentResponse]): StudentResponse | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Test]): Test | null {
    return value.length === 0 ? null : from_candid_Test_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    testType: _TestType;
    instructions: string;
    questions: Array<_Question>;
}): {
    id: bigint;
    title: string;
    testType: TestType;
    instructions: string;
    questions: Array<Question>;
} {
    return {
        id: value.id,
        title: value.title,
        testType: from_candid_TestType_n13(_uploadFile, _downloadFile, value.testType),
        instructions: value.instructions,
        questions: from_candid_vec_n15(_uploadFile, _downloadFile, value.questions)
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    marks: bigint;
    text: string;
    correctAnswer: string;
    questionType: _QuestionType;
    options: Array<string>;
}): {
    id: bigint;
    marks: bigint;
    text: string;
    correctAnswer: string;
    questionType: QuestionType;
    options: Array<string>;
} {
    return {
        id: value.id,
        marks: value.marks,
        text: value.text,
        correctAnswer: value.correctAnswer,
        questionType: from_candid_QuestionType_n18(_uploadFile, _downloadFile, value.questionType),
        options: value.options
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    reading: null;
} | {
    mixed: null;
} | {
    writing: null;
} | {
    listening: null;
}): TestType {
    return "reading" in value ? TestType.reading : "mixed" in value ? TestType.mixed : "writing" in value ? TestType.writing : "listening" in value ? TestType.listening : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sentenceCompletion: null;
} | {
    shortAnswer: null;
} | {
    longAnswer: null;
} | {
    multipleChoice: null;
} | {
    matching: null;
} | {
    trueFalseNotGiven: null;
}): QuestionType {
    return "sentenceCompletion" in value ? QuestionType.sentenceCompletion : "shortAnswer" in value ? QuestionType.shortAnswer : "longAnswer" in value ? QuestionType.longAnswer : "multipleChoice" in value ? QuestionType.multipleChoice : "matching" in value ? QuestionType.matching : "trueFalseNotGiven" in value ? QuestionType.trueFalseNotGiven : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Test>): Array<Test> {
    return value.map((x)=>from_candid_Test_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Question>): Array<Question> {
    return value.map((x)=>from_candid_Question_n16(_uploadFile, _downloadFile, x));
}
function to_candid_QuestionType_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuestionType): _QuestionType {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_Question_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Question): _Question {
    return to_candid_record_n7(_uploadFile, _downloadFile, value);
}
function to_candid_TestType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TestType): _TestType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Test_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Test): _Test {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    testType: TestType;
    instructions: string;
    questions: Array<Question>;
}): {
    id: bigint;
    title: string;
    testType: _TestType;
    instructions: string;
    questions: Array<_Question>;
} {
    return {
        id: value.id,
        title: value.title,
        testType: to_candid_TestType_n3(_uploadFile, _downloadFile, value.testType),
        instructions: value.instructions,
        questions: to_candid_vec_n5(_uploadFile, _downloadFile, value.questions)
    };
}
function to_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    marks: bigint;
    text: string;
    correctAnswer: string;
    questionType: QuestionType;
    options: Array<string>;
}): {
    id: bigint;
    marks: bigint;
    text: string;
    correctAnswer: string;
    questionType: _QuestionType;
    options: Array<string>;
} {
    return {
        id: value.id,
        marks: value.marks,
        text: value.text,
        correctAnswer: value.correctAnswer,
        questionType: to_candid_QuestionType_n8(_uploadFile, _downloadFile, value.questionType),
        options: value.options
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TestType): {
    reading: null;
} | {
    mixed: null;
} | {
    writing: null;
} | {
    listening: null;
} {
    return value == TestType.reading ? {
        reading: null
    } : value == TestType.mixed ? {
        mixed: null
    } : value == TestType.writing ? {
        writing: null
    } : value == TestType.listening ? {
        listening: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuestionType): {
    sentenceCompletion: null;
} | {
    shortAnswer: null;
} | {
    longAnswer: null;
} | {
    multipleChoice: null;
} | {
    matching: null;
} | {
    trueFalseNotGiven: null;
} {
    return value == QuestionType.sentenceCompletion ? {
        sentenceCompletion: null
    } : value == QuestionType.shortAnswer ? {
        shortAnswer: null
    } : value == QuestionType.longAnswer ? {
        longAnswer: null
    } : value == QuestionType.multipleChoice ? {
        multipleChoice: null
    } : value == QuestionType.matching ? {
        matching: null
    } : value == QuestionType.trueFalseNotGiven ? {
        trueFalseNotGiven: null
    } : value;
}
function to_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Question>): Array<_Question> {
    return value.map((x)=>to_candid_Question_n6(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
